[build-system]
requires = [
  "setuptools>=61.0.0",
]
build-backend = "setuptools.build_meta"

[project.urls]
Repository = "https://github.com/diffplug/selfie"
[project]
name = "pytest-selfie"
description = "A pytest plugin for selfie snapshot testing."
version = "0.1.0"
readme = "README.rst"
requires-python = ">=3.8"
authors = [
    { name = "Selina Delgado", email = "sdelgado411@gmail.com" },
    { name = "Harvir Sahota", email = "hsahota2312@gmail.com" },
    { name = "Ned Twigg", email = "ned.twigg@diffplug.com" },
    { name = "Edwin Ye", email = "EdwinYeDeveloper@gmail.com" },
]
maintainers = [
    { name = "Selina Delgado", email = "sdelgado411@gmail.com" },
    { name = "Harvir Sahota", email = "hsahota2312@gmail.com" },
    { name = "Ned Twigg", email = "ned.twigg@diffplug.com" },
    { name = "Edwin Ye", email = "EdwinYeDeveloper@gmail.com" },
]
license = {file = "../../LICENSE"}
classifiers = [
    "Framework :: Pytest",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Testing",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3 :: Only",
    "License :: OSI Approved :: Apache Software License",
]
dependencies = [
    "pytest>=6.2.0",
]
[project.entry-points.pytest11]
django = "pytest_pytest_selfie.plugin"
