name: "Validate Gradle Wrapper"
on:
  push:
    paths:
      - 'jvm/gradlew'
      - 'jvm/gradlew.bat'
      - 'jvm/gradle/wrapper/'
  pull_request:
    paths:
      - 'jvm/gradlew'
      - 'jvm/gradlew.bat'
      - 'jvm/gradle/wrapper/'
permissions:
  contents: read
defaults:
  run:
    working-directory: jvm
jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
