on:
  push:
    branches: [main]
    paths:
      - "python/**"
defaults:
  run:
    working-directory: python
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen
      - name: Install doxygen-awesome-css
        run: npm install
      - name: Generate Documentation
        run: doxygen Doxyfile
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 0a95e814ccf2b6a95d2dc3bea0a4a2b4
          projectName: selfie-pydoc
          directory: python/html
